import { auth, db, storage } from './firebase.js';
import { onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js';
import { collection, addDoc, getDocs, query, orderBy, serverTimestamp, doc, getDoc, updateDoc, deleteDoc, setDoc } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';
import { ref, uploadBytes, getDownloadURL } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-storage.js';
import { money, fmtDate, contains, esc, dtValue } from './helpers.js';

const state={me:null,search:'',camions:[],chauffeurs:[],voyages:[],entretien:[],depenses:[],parametres:null};
const views=['dashboard','camions','chauffeurs','voyages','entretien','depenses','documents','parametres'];
let editing={camions:null,chauffeurs:null,voyages:null,entretien:null,depenses:null};

onAuthStateChanged(auth, async user=>{
  if(!user){window.location.href='../index.html';return;}
  const meSnap=await getDoc(doc(db,'users',user.uid));
  if(!meSnap.exists()||meSnap.data().role!=='admin'){ await signOut(auth); window.location.href='../index.html'; return; }
  state.me={uid:user.uid,...meSnap.data()};
  welcomeText.textContent=`Bienvenue ${state.me.name || state.me.email || 'Admin'}`;
  bindBase();
  await loadAll();
  renderAll();
});

function bindBase(){
  document.querySelectorAll('.nav-btn').forEach(btn=>btn.addEventListener('click',()=>switchView(btn.dataset.view)));
  globalSearch.addEventListener('input',e=>{state.search=e.target.value; renderAll();});
  logoutBtn.addEventListener('click',()=>signOut(auth).then(()=>window.location.href='../index.html'));
  menuBtn?.addEventListener('click',()=>sidebar.classList.toggle('open'));
}
function switchView(view){ views.forEach(v=>document.getElementById(v+'View').classList.toggle('active',v===view)); document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===view)); pageTitle.textContent=view.charAt(0).toUpperCase()+view.slice(1); sidebar.classList.remove('open'); }
async function loadAll(){
  [state.camions,state.chauffeurs,state.voyages,state.entretien,state.depenses]=await Promise.all([
    readCol('camions'), readCol('chauffeurs'), readCol('voyages'), readCol('entretien'), readCol('depenses')
  ]);
  const p=await getDoc(doc(db,'parametres','general')); state.parametres=p.exists()?p.data():null;
}
async function readCol(name){ const qy=query(collection(db,name), orderBy('createdAt','desc')); const snap=await getDocs(qy).catch(()=>getDocs(collection(db,name))); return snap.docs.map(d=>({id:d.id,...d.data()})); }
function f(list, keys){ if(!state.search) return list; return list.filter(x=>keys.some(k=>contains(x[k], state.search))); }
function card(title,val,small=''){ return `<div class="card stat"><div class="muted">${title}</div><div class="value">${val}</div>${small?`<div class="muted small">${small}</div>`:''}</div>`; }
function field(id,label,type='text',cls=''){ return `<label class="${cls}"><span>${label}</span><input id="${id}" type="${type}"></label>`; }
function num(v){ return Number(v||0); }

function renderAll(){ renderDashboard(); renderCamions(); renderChauffeurs(); renderVoyages(); renderEntretien(); renderDepenses(); renderDocuments(); renderParametres(); bindDynamic(); }
function renderDashboard(){
 const revenu = state.voyages.reduce((s,v)=>s+num(v.prixCourse)+num(v.prixCourseRetour),0);
 const coutVoyages = state.voyages.reduce((s,v)=>s+num(v.gasoil)+num(v.fraisMission)+num(v.gasoilRetour)+num(v.fraisMissionRetour),0);
 const coutEntretien = state.entretien.reduce((s,v)=>s+num(v.cout),0);
 const coutDepenses = state.depenses.reduce((s,v)=>s+num(v.montant),0);
 const benefice = revenu-coutVoyages-coutEntretien-coutDepenses;
 dashboardView.innerHTML=`<div class="stats-grid">${card('Revenu total',money(revenu))}${card('Coût voyages',money(coutVoyages))}${card('Entretien',money(coutEntretien))}${card('Bénéfice estimé',money(benefice))}</div>
 <div class="grid-2 mt16"><div class="card"><div class="section-title"><h2>Résumé</h2></div><div class="table-list">
 <div class="item"><div><h4>Camions</h4><p>${state.camions.length} fiche(s)</p></div><span class="badge">Parc</span></div>
 <div class="item"><div><h4>Chauffeurs</h4><p>${state.chauffeurs.length} fiche(s)</p></div><span class="badge">Équipe</span></div>
 <div class="item"><div><h4>Voyages</h4><p>${state.voyages.length} fiche(s)</p></div><span class="badge">Transport</span></div>
 <div class="item"><div><h4>Dépenses</h4><p>${state.entretien.length+state.depenses.length} opération(s)</p></div><span class="badge">Finance</span></div></div></div>
 <div class="card"><div class="section-title"><h2>Derniers voyages</h2></div><div class="stack">${state.voyages.slice(0,5).map(v=>`<div class="item"><div><h4>${esc(v.client||'-')} → ${esc(v.destination||'-')}</h4><p>${esc(v.nomChauffeur||'-')}</p><p>${fmtDate(v.dateDepart)}</p></div><strong>${money(num(v.prixCourse)+num(v.prixCourseRetour))}</strong></div>`).join('') || '<div class="empty">Aucun voyage</div>'}</div></div></div>`;
}
function renderCamions(){ const list=f(state.camions,['numeroCamion','numeroPlaque','marqueModele','numeroRemorque','plaqueRemorque','remarque']); camionsView.innerHTML=`<div class="grid-2"><section class="card"><div class="section-title"><h2>${editing.camions?'Modifier':'Ajouter'} un camion</h2></div><form id="camionForm" class="form-grid">${field('numeroCamion','Numéro de camion')}${field('numeroPlaque','Numéro de plaque')}${field('marqueModele','Marque de camion et modèle')}${field('numeroRemorque','Numéro de remorque')}${field('plaqueRemorque','Plaque de remorque')}<label class="full"><span>Remarque</span><textarea id="remarque"></textarea></label><div class="full actions"><button class="btn primary">${editing.camions?'Mettre à jour':'Enregistrer'}</button>${editing.camions?'<button type="button" id="cancelCamion" class="btn secondary">Annuler</button>':''}</div></form></section><section class="card"><div class="section-title"><h2>Liste des camions</h2><p class="muted">${list.length} résultat(s)</p></div><div class="stack">${list.map(i=>`<div class="item"><div><h4>${esc(i.numeroCamion||'-')} • ${esc(i.marqueModele||'-')}</h4><p>Plaque: ${esc(i.numeroPlaque||'-')}</p><p>Remorque: ${esc(i.numeroRemorque||'-')} • ${esc(i.plaqueRemorque||'-')}</p><p>${esc(i.remarque||'')}</p></div><div class="actions"><button class="btn small secondary edit" data-col="camions" data-id="${i.id}">Modifier</button><button class="btn small danger del" data-col="camions" data-id="${i.id}">Supprimer</button></div></div>`).join('') || '<div class="empty">Aucun camion</div>'}</div></section></div>`; fillCamion(); }
function fillCamion(){ if(!editing.camions) return; const x=state.camions.find(i=>i.id===editing.camions); if(!x) return; ['numeroCamion','numeroPlaque','marqueModele','numeroRemorque','plaqueRemorque','remarque'].forEach(k=>document.getElementById(k).value=x[k]||''); }
function renderChauffeurs(){ const list=f(state.chauffeurs,['nom','numeroChauffeur','numeroPermis','adresse','telephone','userId']); chauffeursView.innerHTML=`<div class="grid-2"><section class="card"><div class="section-title"><h2>${editing.chauffeurs?'Modifier':'Ajouter'} un chauffeur</h2></div><form id="chauffeurForm" class="form-grid">${field('userId','UID Firebase du chauffeur')}${field('nom','Nom du chauffeur')}${field('numeroChauffeur','Numéro de chauffeur')}${field('numeroPermis','Numéro de permis')}${field('telephone','Téléphone')}${field('adresse','Adresse','text','full')}<div class="full actions"><button class="btn primary">${editing.chauffeurs?'Mettre à jour':'Enregistrer'}</button>${editing.chauffeurs?'<button type="button" id="cancelChauffeur" class="btn secondary">Annuler</button>':''}</div></form></section><section class="card"><div class="section-title"><h2>Liste des chauffeurs</h2></div><div class="stack">${list.map(i=>`<div class="item"><div><h4>${esc(i.nom||'-')}</h4><p>UID: ${esc(i.userId||'-')}</p><p>Chauffeur: ${esc(i.numeroChauffeur||'-')} • Permis: ${esc(i.numeroPermis||'-')}</p><p>${esc(i.telephone||'-')} • ${esc(i.adresse||'-')}</p></div><div class="actions"><button class="btn small secondary edit" data-col="chauffeurs" data-id="${i.id}">Modifier</button><button class="btn small danger del" data-col="chauffeurs" data-id="${i.id}">Supprimer</button></div></div>`).join('') || '<div class="empty">Aucun chauffeur</div>'}</div></section></div>`; fillChauffeur(); }
function fillChauffeur(){ if(!editing.chauffeurs) return; const x=state.chauffeurs.find(i=>i.id===editing.chauffeurs); if(!x) return; ['userId','nom','numeroChauffeur','numeroPermis','telephone','adresse'].forEach(k=>document.getElementById(k).value=x[k]||''); }
function renderVoyages(){ const drivers=state.chauffeurs.map(c=>`<option value="${esc(c.userId)}">${esc(c.nom)} (${esc(c.numeroChauffeur||'')})</option>`).join(''); const trucks=state.camions.map(c=>`<option value="${esc(c.id)}">${esc(c.numeroCamion||c.marqueModele)}</option>`).join(''); const list=f(state.voyages,['client','destination','retourClient','retourDestination','nomChauffeur']); voyagesView.innerHTML=`<div class="grid-2"><section class="card"><div class="section-title"><h2>${editing.voyages?'Modifier':'Ajouter'} un voyage</h2></div><form id="voyageForm" class="form-grid"><label><span>Chauffeur</span><select id="chauffeurId"><option value="">Choisir</option>${drivers}</select></label><label><span>Camion</span><select id="camionId"><option value="">Choisir</option>${trucks}</select></label>${field('client','Client')}${field('destination','Destination')}${field('dateDepart','Date de départ','datetime-local')}${field('dateArrivee','Date d’arrivée','datetime-local')}${field('prixCourse','Prix de course','number')}${field('gasoil','Gasoil aller','number')}${field('fraisMission','Frais de mission aller','number')}${field('auteurDepenses','Auteur dépenses')}${field('retourClient','Client retour')}${field('retourDestination','Destination retour')}${field('dateRetour','Date de retour','datetime-local')}${field('dateRetourArrivee','Date arrivée retour','datetime-local')}${field('prixCourseRetour','Prix de course retour','number')}${field('gasoilRetour','Gasoil retour','number')}${field('fraisMissionRetour','Frais de mission retour','number')}${field('kilometrageApres10Voyages','Kilométrage après chèque 10 voyages','number','full')}<div class="full actions"><button class="btn primary">${editing.voyages?'Mettre à jour':'Enregistrer'}</button>${editing.voyages?'<button type="button" id="cancelVoyage" class="btn secondary">Annuler</button>':''}</div></form></section><section class="card"><div class="section-title"><h2>Liste des voyages</h2></div><div class="stack">${list.map(v=>`<div class="item"><div><h4>${esc(v.client||'-')} → ${esc(v.destination||'-')}</h4><p>Chauffeur: ${esc(v.nomChauffeur||'-')}</p><p>Départ: ${fmtDate(v.dateDepart)} • Arrivée: ${fmtDate(v.dateArrivee)}</p><p>Aller: ${money(v.prixCourse)} • Retour: ${money(v.prixCourseRetour)}</p><p>Gasoil total: ${money(num(v.gasoil)+num(v.gasoilRetour))} • Frais mission: ${money(num(v.fraisMission)+num(v.fraisMissionRetour))}</p></div><div class="actions"><button class="btn small secondary edit" data-col="voyages" data-id="${v.id}">Modifier</button><button class="btn small danger del" data-col="voyages" data-id="${v.id}">Supprimer</button></div></div>`).join('') || '<div class="empty">Aucun voyage</div>'}</div></section></div>`; fillVoyage(); }
function fillVoyage(){ if(!editing.voyages) return; const x=state.voyages.find(i=>i.id===editing.voyages); if(!x) return; ['chauffeurId','camionId','client','destination','prixCourse','gasoil','fraisMission','auteurDepenses','retourClient','retourDestination','prixCourseRetour','gasoilRetour','fraisMissionRetour','kilometrageApres10Voyages'].forEach(k=>{ const el=document.getElementById(k); if(el) el.value=x[k]||'';}); ['dateDepart','dateArrivee','dateRetour','dateRetourArrivee'].forEach(k=>{ const el=document.getElementById(k); if(el) el.value=dtValue(x[k]);}); }
function renderEntretien(){ const trucks=state.camions.map(c=>`<option value="${esc(c.id)}">${esc(c.numeroCamion||c.marqueModele)}</option>`).join(''); const list=f(state.entretien,['type','description','garage']); entretienView.innerHTML=`<div class="grid-2"><section class="card"><div class="section-title"><h2>${editing.entretien?'Modifier':'Ajouter'} un entretien</h2></div><form id="entretienForm" class="form-grid"><label><span>Camion</span><select id="entCamionId"><option value="">Choisir</option>${trucks}</select></label><label><span>Type</span><select id="type"><option value="pneus">Pneus</option><option value="vidange">Vidange</option><option value="pieces mecaniques">Pièces mécaniques</option><option value="reparation">Frais de réparation</option><option value="hotel reparation">Hôtel réparation</option></select></label><label class="full"><span>Description</span><textarea id="description"></textarea></label>${field('cout','Coût','number')}${field('date','Date','datetime-local')}${field('garage','Garage / lieu')}<label><span>Remorque</span><select id="remorque"><option value="false">Non</option><option value="true">Oui</option></select></label><div class="full"><label><span>Document / facture</span><input id="entretienFile" type="file"></label></div><div class="full actions"><button class="btn primary">${editing.entretien?'Mettre à jour':'Enregistrer'}</button>${editing.entretien?'<button type="button" id="cancelEntretien" class="btn secondary">Annuler</button>':''}</div></form></section><section class="card"><div class="section-title"><h2>Liste entretien</h2></div><div class="stack">${list.map(v=>`<div class="item"><div><h4>${esc(v.type||'-')}</h4><p>${esc(v.description||'-')}</p><p>${fmtDate(v.date)} • ${money(v.cout)}</p><p>${esc(v.garage||'-')} ${v.fileUrl?`• <a href="${v.fileUrl}" target="_blank">Document</a>`:''}</p></div><div class="actions"><button class="btn small secondary edit" data-col="entretien" data-id="${v.id}">Modifier</button><button class="btn small danger del" data-col="entretien" data-id="${v.id}">Supprimer</button></div></div>`).join('') || '<div class="empty">Aucun entretien</div>'}</div></section></div>`; fillEntretien(); }
function fillEntretien(){ if(!editing.entretien) return; const x=state.entretien.find(i=>i.id===editing.entretien); if(!x) return; if(entCamionId) entCamionId.value=x.camionId||''; ['type','description','cout','garage'].forEach(k=>document.getElementById(k).value=x[k]||''); date.value=dtValue(x.date); remorque.value=String(!!x.remorque); }
function renderDepenses(){ const trucks=state.camions.map(c=>`<option value="${esc(c.id)}">${esc(c.numeroCamion||c.marqueModele)}</option>`).join(''); const drivers=state.chauffeurs.map(c=>`<option value="${esc(c.userId)}">${esc(c.nom)}</option>`).join(''); const list=f(state.depenses,['type','description']); depensesView.innerHTML=`<div class="grid-2"><section class="card"><div class="section-title"><h2>${editing.depenses?'Modifier':'Ajouter'} une dépense</h2></div><form id="depenseForm" class="form-grid"><label><span>Type</span><select id="depType"><option value="assurance chauffeur">Assurance chauffeur</option><option value="frais comptable">Frais comptable</option><option value="declaration impots">Déclaration d’impôts</option><option value="salaire chauffeur">Salaire chauffeur</option><option value="assurance camion">Assurance du camion</option><option value="assurance marchandise">Assurance de marchandise</option></select></label>${field('montant','Montant','number')}${field('depDate','Date','datetime-local')}<label><span>Camion lié</span><select id="depCamionId"><option value="">Aucun</option>${trucks}</select></label><label><span>Chauffeur lié</span><select id="depChauffeurId"><option value="">Aucun</option>${drivers}</select></label><label class="full"><span>Description</span><textarea id="depDescription"></textarea></label><div class="full"><label><span>Reçu / document</span><input id="depenseFile" type="file"></label></div><div class="full actions"><button class="btn primary">${editing.depenses?'Mettre à jour':'Enregistrer'}</button>${editing.depenses?'<button type="button" id="cancelDepense" class="btn secondary">Annuler</button>':''}</div></form></section><section class="card"><div class="section-title"><h2>Liste dépenses</h2></div><div class="stack">${list.map(v=>`<div class="item"><div><h4>${esc(v.type||'-')}</h4><p>${esc(v.description||'-')}</p><p>${fmtDate(v.date)} • ${money(v.montant)}</p><p>${v.fileUrl?`<a href="${v.fileUrl}" target="_blank">Document</a>`:''}</p></div><div class="actions"><button class="btn small secondary edit" data-col="depenses" data-id="${v.id}">Modifier</button><button class="btn small danger del" data-col="depenses" data-id="${v.id}">Supprimer</button></div></div>`).join('') || '<div class="empty">Aucune dépense</div>'}</div></section></div>`; fillDepense(); }
function fillDepense(){ if(!editing.depenses) return; const x=state.depenses.find(i=>i.id===editing.depenses); if(!x) return; depType.value=x.type||''; montant.value=x.montant||''; depDate.value=dtValue(x.date); depCamionId.value=x.camionId||''; depChauffeurId.value=x.chauffeurId||''; depDescription.value=x.description||''; }
function renderDocuments(){ const tripDocs=state.voyages.filter(v=>v.fileUrl); const entDocs=state.entretien.filter(v=>v.fileUrl); const depDocs=state.depenses.filter(v=>v.fileUrl); documentsView.innerHTML=`<div class="grid-2"><section class="card"><div class="section-title"><h2>Documents voyages</h2></div><div class="stack">${tripDocs.map(v=>`<div class="item"><div><h4>${esc(v.client||'-')}</h4><p>${esc(v.nomChauffeur||'-')}</p></div><a class="btn small secondary" target="_blank" href="${v.fileUrl}">Ouvrir</a></div>`).join('') || '<div class="empty">Aucun document voyage</div>'}</div></section><section class="card"><div class="section-title"><h2>Documents entretien / dépenses</h2></div><div class="stack">${[...entDocs,...depDocs].map(v=>`<div class="item"><div><h4>${esc(v.type||v.client||'-')}</h4><p>${fmtDate(v.date||v.createdAt)}</p></div><a class="btn small secondary" target="_blank" href="${v.fileUrl}">Ouvrir</a></div>`).join('') || '<div class="empty">Aucun document</div>'}</div></section></div>`; }
function renderParametres(){ const p=state.parametres||{}; parametresView.innerHTML=`<div class="grid-2"><section class="card"><div class="section-title"><h2>Paramètres généraux</h2></div><form id="paramForm" class="form-grid">${field('nomEntreprise','Nom entreprise')}${field('devise','Devise')}${field('telephoneEntreprise','Téléphone')}${field('emailEntreprise','Email')}${field('adresseEntreprise','Adresse','text','full')}<div class="full actions"><button class="btn primary">Enregistrer</button></div></form></section><section class="card"><div class="section-title"><h2>Aide démarrage</h2></div><div class="stack"><div class="item"><div><h4>Collections prévues</h4><p>users, camions, chauffeurs, voyages, entretien, depenses, parametres/general</p></div></div><div class="item"><div><h4>Uploads</h4><p>Documents par voyage, entretien et dépense inclus.</p></div></div><div class="item"><div><h4>Rôles</h4><p>admin = accès total, chauffeur = ses propres voyages.</p></div></div></div></section></div>`; ['nomEntreprise','devise','telephoneEntreprise','emailEntreprise','adresseEntreprise'].forEach(k=>{ const el=document.getElementById(k); if(el) el.value=p[k]||''; }); }

function bindDynamic(){
  document.getElementById('camionForm')?.addEventListener('submit', saveCamion);
  document.getElementById('chauffeurForm')?.addEventListener('submit', saveChauffeur);
  document.getElementById('voyageForm')?.addEventListener('submit', saveVoyage);
  document.getElementById('entretienForm')?.addEventListener('submit', saveEntretien);
  document.getElementById('depenseForm')?.addEventListener('submit', saveDepense);
  document.getElementById('paramForm')?.addEventListener('submit', saveParams);
  document.querySelectorAll('.edit').forEach(b=>b.addEventListener('click', ()=>{ editing[b.dataset.col]=b.dataset.id; renderAll(); switchView(b.dataset.col==='depenses'?'depenses':b.dataset.col); }));
  document.querySelectorAll('.del').forEach(b=>b.addEventListener('click', ()=>removeDoc(b.dataset.col,b.dataset.id)));
  document.getElementById('cancelCamion')?.addEventListener('click',()=>{editing.camions=null; renderCamions(); bindDynamic();});
  document.getElementById('cancelChauffeur')?.addEventListener('click',()=>{editing.chauffeurs=null; renderChauffeurs(); bindDynamic();});
  document.getElementById('cancelVoyage')?.addEventListener('click',()=>{editing.voyages=null; renderVoyages(); bindDynamic();});
  document.getElementById('cancelEntretien')?.addEventListener('click',()=>{editing.entretien=null; renderEntretien(); bindDynamic();});
  document.getElementById('cancelDepense')?.addEventListener('click',()=>{editing.depenses=null; renderDepenses(); bindDynamic();});
}
async function saveCamion(e){ e.preventDefault(); const payload={numeroCamion:numeroCamion.value.trim(),numeroPlaque:numeroPlaque.value.trim(),marqueModele:marqueModele.value.trim(),numeroRemorque:numeroRemorque.value.trim(),plaqueRemorque:plaqueRemorque.value.trim(),remarque:remarque.value.trim(),updatedAt:serverTimestamp()}; if(editing.camions){ await updateDoc(doc(db,'camions',editing.camions),payload); editing.camions=null; } else { payload.createdAt=serverTimestamp(); await addDoc(collection(db,'camions'),payload);} await loadAll(); renderAll(); }
async function saveChauffeur(e){ e.preventDefault(); const payload={userId:userId.value.trim(),nom:nom.value.trim(),numeroChauffeur:numeroChauffeur.value.trim(),numeroPermis:numeroPermis.value.trim(),telephone:telephone.value.trim(),adresse:adresse.value.trim(),updatedAt:serverTimestamp()}; if(editing.chauffeurs){ await updateDoc(doc(db,'chauffeurs',editing.chauffeurs),payload); editing.chauffeurs=null; } else { payload.createdAt=serverTimestamp(); await addDoc(collection(db,'chauffeurs'),payload);} await loadAll(); renderAll(); }
async function saveVoyage(e){ e.preventDefault(); const driver=state.chauffeurs.find(c=>c.userId===chauffeurId.value) || {}; const payload={chauffeurId:chauffeurId.value,nomChauffeur:driver.nom||'',camionId:camionId.value,client:client.value.trim(),destination:destination.value.trim(),dateDepart:dateDepart.value?new Date(dateDepart.value):null,dateArrivee:dateArrivee.value?new Date(dateArrivee.value):null,prixCourse:num(prixCourse.value),gasoil:num(gasoil.value),fraisMission:num(fraisMission.value),auteurDepenses:auteurDepenses.value.trim(),retourClient:retourClient.value.trim(),retourDestination:retourDestination.value.trim(),dateRetour:dateRetour.value?new Date(dateRetour.value):null,dateRetourArrivee:dateRetourArrivee.value?new Date(dateRetourArrivee.value):null,prixCourseRetour:num(prixCourseRetour.value),gasoilRetour:num(gasoilRetour.value),fraisMissionRetour:num(fraisMissionRetour.value),kilometrageApres10Voyages:num(kilometrageApres10Voyages.value),updatedAt:serverTimestamp()}; if(editing.voyages){ await updateDoc(doc(db,'voyages',editing.voyages),payload); editing.voyages=null; } else { payload.createdBy=state.me.uid; payload.createdAt=serverTimestamp(); await addDoc(collection(db,'voyages'),payload);} await loadAll(); renderAll(); }
async function saveEntretien(e){ e.preventDefault(); let fileUrl=state.entretien.find(x=>x.id===editing.entretien)?.fileUrl || ''; if(entretienFile.files[0]){ const path=`entretien/${editing.entretien||Date.now()}/${entretienFile.files[0].name}`; const snap=await uploadBytes(ref(storage,path),entretienFile.files[0]); fileUrl=await getDownloadURL(snap.ref);} const payload={camionId:entCamionId.value,type:type.value,description:description.value.trim(),cout:num(cout.value),date:date.value?new Date(date.value):null,garage:garage.value.trim(),remorque:remorque.value==='true',fileUrl,updatedAt:serverTimestamp()}; if(editing.entretien){ await updateDoc(doc(db,'entretien',editing.entretien),payload); editing.entretien=null; } else { payload.createdAt=serverTimestamp(); await addDoc(collection(db,'entretien'),payload);} await loadAll(); renderAll(); }
async function saveDepense(e){ e.preventDefault(); let fileUrl=state.depenses.find(x=>x.id===editing.depenses)?.fileUrl || ''; if(depenseFile.files[0]){ const path=`depenses/${editing.depenses||Date.now()}/${depenseFile.files[0].name}`; const snap=await uploadBytes(ref(storage,path),depenseFile.files[0]); fileUrl=await getDownloadURL(snap.ref);} const payload={type:depType.value,montant:num(montant.value),description:depDescription.value.trim(),date:depDate.value?new Date(depDate.value):null,camionId:depCamionId.value,chauffeurId:depChauffeurId.value,fileUrl,updatedAt:serverTimestamp()}; if(editing.depenses){ await updateDoc(doc(db,'depenses',editing.depenses),payload); editing.depenses=null; } else { payload.createdAt=serverTimestamp(); await addDoc(collection(db,'depenses'),payload);} await loadAll(); renderAll(); }
async function saveParams(e){ e.preventDefault(); await setDoc(doc(db,'parametres','general'),{nomEntreprise:nomEntreprise.value.trim(),devise:devise.value.trim()||'CAD',telephoneEntreprise:telephoneEntreprise.value.trim(),emailEntreprise:emailEntreprise.value.trim(),adresseEntreprise:adresseEntreprise.value.trim(),updatedAt:serverTimestamp()},{merge:true}); await loadAll(); renderParametres(); alert('Paramètres enregistrés'); }
async function removeDoc(col,id){ if(!confirm('Supprimer cet élément ?')) return; await deleteDoc(doc(db,col,id)); await loadAll(); renderAll(); }
