import { auth, db, storage } from './firebase.js';
import { onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js';
import { collection, addDoc, getDocs, query, where, doc, getDoc, updateDoc, deleteDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';
import { ref, uploadBytes, getDownloadURL } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-storage.js';
import { money, fmtDate, esc, dtValue } from './helpers.js';

let me=null, trips=[], editId=null;
onAuthStateChanged(auth, async user=>{
  if(!user){window.location.href='../index.html';return;}
  const snap=await getDoc(doc(db,'users',user.uid));
  if(!snap.exists()){await signOut(auth); window.location.href='../index.html';return;}
  me={uid:user.uid,...snap.data()};
  if(me.role!=='chauffeur'){window.location.href='./admin.html'; return;}
  driverWelcome.textContent=`Bienvenue ${me.name || me.email || 'Chauffeur'}`;
  renderForm();
  await loadTrips();
  renderStats();
  renderTrips();
  logoutBtn.addEventListener('click',()=>signOut(auth).then(()=>window.location.href='../index.html'));
});
function renderForm(){ driverTripForm.innerHTML=`<label><span>Client</span><input id="client"></label><label><span>Destination</span><input id="destination"></label><label><span>Date départ</span><input id="dateDepart" type="datetime-local"></label><label><span>Date arrivée</span><input id="dateArrivee" type="datetime-local"></label><label><span>Prix course</span><input id="prixCourse" type="number"></label><label><span>Gasoil</span><input id="gasoil" type="number"></label><label><span>Frais mission</span><input id="fraisMission" type="number"></label><label><span>Client retour</span><input id="retourClient"></label><label><span>Destination retour</span><input id="retourDestination"></label><label><span>Date retour</span><input id="dateRetour" type="datetime-local"></label><label><span>Date arrivée retour</span><input id="dateRetourArrivee" type="datetime-local"></label><label><span>Prix retour</span><input id="prixCourseRetour" type="number"></label><label><span>Gasoil retour</span><input id="gasoilRetour" type="number"></label><label><span>Frais mission retour</span><input id="fraisMissionRetour" type="number"></label><label><span>Camion (ID ou numéro)</span><input id="camionId"></label><label class="full"><span>Kilométrage après chèque 10 voyages</span><input id="kilometrageApres10Voyages" type="number"></label><label class="full"><span>Document voyage</span><input id="voyageFile" type="file"></label><div class="full actions"><button class="btn primary">${editId?'Mettre à jour':'Enregistrer'}</button>${editId?'<button type="button" id="cancelEdit" class="btn secondary">Annuler</button>':''}</div>`; driverTripForm.addEventListener('submit',saveTrip); document.getElementById('cancelEdit')?.addEventListener('click',()=>{editId=null; renderForm();}); if(editId){ const x=trips.find(t=>t.id===editId); if(x){ ['client','destination','prixCourse','gasoil','fraisMission','retourClient','retourDestination','prixCourseRetour','gasoilRetour','fraisMissionRetour','camionId','kilometrageApres10Voyages'].forEach(k=>document.getElementById(k).value=x[k]||''); ['dateDepart','dateArrivee','dateRetour','dateRetourArrivee'].forEach(k=>document.getElementById(k).value=dtValue(x[k])); } } }
async function saveTrip(e){ e.preventDefault(); let fileUrl=trips.find(t=>t.id===editId)?.fileUrl || ''; if(voyageFile.files[0]){ const path=`voyages/${editId||Date.now()}/${voyageFile.files[0].name}`; const snap=await uploadBytes(ref(storage,path),voyageFile.files[0]); fileUrl=await getDownloadURL(snap.ref); }
 const payload={chauffeurId:me.uid,nomChauffeur:me.name || me.email || '',camionId:camionId.value.trim(),client:client.value.trim(),destination:destination.value.trim(),dateDepart:dateDepart.value?new Date(dateDepart.value):null,dateArrivee:dateArrivee.value?new Date(dateArrivee.value):null,prixCourse:Number(prixCourse.value||0),gasoil:Number(gasoil.value||0),fraisMission:Number(fraisMission.value||0),retourClient:retourClient.value.trim(),retourDestination:retourDestination.value.trim(),dateRetour:dateRetour.value?new Date(dateRetour.value):null,dateRetourArrivee:dateRetourArrivee.value?new Date(dateRetourArrivee.value):null,prixCourseRetour:Number(prixCourseRetour.value||0),gasoilRetour:Number(gasoilRetour.value||0),fraisMissionRetour:Number(fraisMissionRetour.value||0),kilometrageApres10Voyages:Number(kilometrageApres10Voyages.value||0),fileUrl,updatedAt:serverTimestamp()};
 if(editId){ await updateDoc(doc(db,'voyages',editId),payload); editId=null; } else { payload.createdBy=me.uid; payload.createdAt=serverTimestamp(); await addDoc(collection(db,'voyages'),payload); }
 renderForm(); await loadTrips(); renderStats(); renderTrips(); }
async function loadTrips(){ const snap=await getDocs(query(collection(db,'voyages'), where('chauffeurId','==',me.uid))); trips=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)); }
function renderStats(){ const revenu=trips.reduce((s,t)=>s+Number(t.prixCourse||0)+Number(t.prixCourseRetour||0),0); const couts=trips.reduce((s,t)=>s+Number(t.gasoil||0)+Number(t.fraisMission||0)+Number(t.gasoilRetour||0)+Number(t.fraisMissionRetour||0),0); driverStats.innerHTML=`<div class="card stat"><div class="muted">Mes voyages</div><div class="value">${trips.length}</div></div><div class="card stat"><div class="muted">Mon revenu</div><div class="value">${money(revenu)}</div></div><div class="card stat"><div class="muted">Mes coûts</div><div class="value">${money(couts)}</div></div><div class="card stat"><div class="muted">Net estimé</div><div class="value">${money(revenu-couts)}</div></div>`; }
function renderTrips(){ driverTripList.innerHTML=trips.map(t=>`<div class="item"><div><h3>${esc(t.client||'-')} → ${esc(t.destination||'-')}</h3><p>Départ: ${fmtDate(t.dateDepart)} • Arrivée: ${fmtDate(t.dateArrivee)}</p><p>Aller: ${money(t.prixCourse)} • Retour: ${money(t.prixCourseRetour)}</p><p>Gasoil total: ${money(Number(t.gasoil||0)+Number(t.gasoilRetour||0))}</p><p>${t.fileUrl?`<a target="_blank" href="${t.fileUrl}">Ouvrir document</a>`:''}</p></div><div class="actions"><button class="btn small secondary mod" data-id="${t.id}">Modifier</button><button class="btn small danger del" data-id="${t.id}">Supprimer</button></div></div>`).join('') || '<div class="empty">Aucun voyage</div>'; document.querySelectorAll('.mod').forEach(b=>b.addEventListener('click',()=>{editId=b.dataset.id; renderForm(); window.scrollTo({top:0,behavior:'smooth'});})); document.querySelectorAll('.del').forEach(b=>b.addEventListener('click',()=>removeTrip(b.dataset.id))); }
async function removeTrip(id){ if(!confirm('Supprimer ce voyage ?')) return; await deleteDoc(doc(db,'voyages',id)); await loadTrips(); renderStats(); renderTrips(); }
